name: "Render manim"
on:
  pull_request:
  push:
jobs:
  render:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: nicknovitski/nix-develop@v1
      with:
        arguments: ".#render --no-pure-eval"
    - name: Render
      run: just render
    - uses: actions/upload-artifact@v4
      with:
        name: rendered_videos
        path: media # or path/to/artifact
